# Generated by Django 5.2.1 on 2025-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_googleaccount_account_googleaccount_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_space_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_space_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
